server:
  port: 8081

spring:
  application:
    name: weixin-applet-voice
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public

# 变声服务配置
voice:
  temp-dir: ./temp/voice

# 日志配置
logging:
  level:
    com.wanyun.voice: debug
